### ISSUE TITLE
Not all references included

### ISSUE THREAD

**Issue by DigniticeRoland** [joshuatz/linkedin-to-jsonresume#12]
Hi,

thank you for your awesome work.
Unfortunatly not all references are included into JSON. I only see two instead of all 6 or 8.

![image](https://user-images.githubusercontent.com/62964017/79141025-45b2f800-7db9-11ea-8d18-2cc588722998.png)

Thank you for double checking.

**Comment by joshuatz** [comment]
Hi @DigniticeRoland 

Sorry for the delay in responding; for some reason I missed getting notifications for this issue and your others. I'll take a look at them all shortly.
