### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by sjlavena** [joshuatz/linkedin-to-jsonresume#22]
If the linkedin profile shows the "show more" link because there are too many jobs (not that many really), the JSON generated doesn't include that info. This happens even if the plugin is called AFTER the show more link is pressed.

So I can't find any work arround this...

Example profile: https://www.linkedin.com/in/sebastianlavena/

This is great work ! Thanks if you can fix this :)

**Comment by joshuatz** [comment]
Thanks for reporting this, and especially for providing an example profile (that helps me a lot).

I can verify I see the same bug that you do. I'm sure there is *some* way I'll be able to fix this, but it might take a little bit of time; at first-glance, LinkedIn is not making it easy to pull the full list of work positions, and it might take some digging on my end to find a reliable way to grab the full info every time.

**Comment by sjlavena** [comment]
Thanks you very much for your reply !

Not sure if it helps, but as a user for me it wouldn't be a problem if I need to click on all the "show more" links that may appear  on the webpage before running the plugin.

I highly appreciate any workaround you may find !

Thanks again,

Sebastian

**Comment by sjlavena** [comment]
Thanks Joshua  ! 

I just saw your commit related to this !!

Does that means that the Chrome plugin should now work or we need to wait for the update to reach the chrome store to get this update ?

**Comment by joshuatz** [comment]
@sjlavena Sorry, no not yet. After I made that commit, I got side-tracked by some other projects. I'm working on finishing this up today though, and hopefully should be commenting at you again shortly with an update and release info.

**Comment by joshuatz** [comment]
@sjlavena I finally finished implementing a fix / workaround for this.

It is working in the newest version (`v1.3.0`), which I've just uploaded to the Chrome Webstore for distribution, but it can take weeks to get processed, so if you want to use it ASAP, you can follow [my side-loading instructions](https://github.com/joshuatz/linkedin-to-jsonresume#chrome-side-loading-instructions). And you can find the `v1.3.0` ZIP [here](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v1.3.0).
