### ISSUE TITLE
When exporting my LinkedIn profile, I end up with someone else's work experience

### ISSUE THREAD

**Issue by DandyDev** [joshuatz/linkedin-to-jsonresume#26]
I have a strange issue. When using the extension on [my LinkedIn profile](https://www.linkedin.com/in/danieldebie/), the resulting JSON Resume file contains my own _summary_ and _education_ sections, but someone else's work history. In this case, it's the work history of an [ex-colleague of mine](https://www.linkedin.com/in/johnbol/). I assume this is a bug?

**Comment by joshuatz** [comment]
Thanks for reporting this. I was immediately able to reproduce the exact same results as you got (your ex-colleague's work experience got pulled in). This is... bizarre, to say the least.

I'll look into this; my guess is the wrong profile URN ID is getting pulled in somehow, which LinkedIn is making it harder and harder to extract reliably.

**Comment by joshuatz** [comment]
@DandyDev This indeed was an issue with incorrect profileUrnId extraction; a fix has been implemented and [a new release authored](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v1.4.1) (v1.4.1).

Thanks again for reporting (and including the profile links - that helped me a lot).

**Comment by DandyDev** [comment]
Awesome, this works correctly for me now!
