### ISSUE TITLE
Some dates are not parsed correctly

### ISSUE THREAD

**Issue by lucbpz** [joshuatz/linkedin-to-jsonresume#3]
* One digit months need to be transformed into two digit months.
When last day of the month is set:
* Max number of days needs to be calculated instead of showing 31 for every month.

This should help validate the schema faster instead of having to validate manually and figure out which dates are incorrect.

**Comment by lucbpz** [comment]
Let me grab this issue and contribute to your project 😄

**Comment by joshuatz** [comment]
@lucbpz Those are both good catches. I completely missed the fact that the schema spec calls for left-padding of months and days. And I welcome contributions - go for it! 👏

I didn't bother to set up contributing guidelines for this repo, but just follow the normal pattern (fork/clone, branch, push to fork, and then PR to merge your branch into master) and try to test locally if you can. I'll do my best to review any PR's you make in a timely manner.

**Comment by joshuatz** [comment]
Closed by PR #5
