### ISSUE TITLE
Parse from URL

### ISSUE THREAD

**Issue by blopa** [joshuatz/linkedin-to-jsonresume#31]
This is awesome and super useful, thanks for making this and proving a wholesome readme.

I was looking into your code and I'm wondering if it is possible to parse all the data from Linkedin by scraping a Linkedin profile URL.

Is it possible? Could you point me how to?

Thanks

**Comment by joshuatz** [comment]
@blopa Thanks for the kind words. This project, as a browser extension, uses the current user's browser environment while they have a LinkedIn page open - the browser itself and its APIs (e.g. `fetch`), the JavaScript engine, and crucially for this project, [the stored cookies](https://github.com/joshuatz/linkedin-to-jsonresume/blob/c6ca3abe15c4b597349e3b2c1b4fe86621aa5925/src/main.js#L1718-L1722).

For scraping by URL, *theoretically*, you could probably re-use the code right now by automating Puppeteer or [Playwright](https://playwright.dev/) to start a browser session, login to LinkedIn, navigate to the profile URL you want to extract, and then run a modified version of my code.

For gathering the data without a browser (e.g. with a NodeJS backend), this project would need a significant re-write to extract the Voyager API stuff into an isomorphic / cross-environment library. That is not off the table as an option, but I don't have time to commit to that right now. However, there is already a non-browser library for the unofficial Voyager API, and that might be the closest to what you are looking for - [tomquirk/linkedin-api](https://github.com/tomquirk/linkedin-api) (Python).

Did this answer your question?
