### ISSUE TITLE
Position/Title missing into the exported JSON structure

### ISSUE THREAD

**Issue by sebDK** [joshuatz/linkedin-to-jsonresume#41]
Hi,

Nice extension!
Title / Position is missing for all work items:
```
"work": [
    {
      "company": "MyCompany",
      "highlights": [],
      "startDate": "2013-11-30",
      "website": "https://www.linkedin.com/company/xxxx/"
    },
```
It would be very cool to get them.
I use version 2.1.1

**Comment by joshuatz** [comment]
By any chance, is this for a multi-lingual profile? Any can you please verify what version of schema export you are using (value for the "Select JSONResume Version" dropdown):

- `Stable (v0.0.16)`
- `Latest (v0.1.3)`
- `Beta (v0.1.3 + extra)`

**Comment by sebDK** [comment]
I used all possible combinations but still getting:
 ```
"work": [
    {
      "name": "Group",
      "startDate": "2013-11-30",
      "endDate": "",
      "highlights": [],
      "url": "https://www.linkedin.com/company/group/"
    },
```
Funny part it that position is coming on vcf card...

**Comment by joshuatz** [comment]
@sebDK Ok, I believe I have successfully isolated the issue causing this and fixed it (and some related issues with work positions). There is a new version with these fixes - [`v.2.1.2`](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v2.1.2).

I have initiated an updated release through the Chrome webstore - please note that this can take a while to show up (usually within 24 hours though).

Please let me know if the updated version does not resolve this issue for you.

**Comment by sebDK** [comment]
@joshuatz many thanks it is now working perfectly.
Thank you.
