### ISSUE TITLE
Block account linkedin

### ISSUE THREAD

**Issue by financeirotalenses** [joshuatz/linkedin-to-jsonresume#50]
I used it for 1 week and linkedin added a notification notice,
warning that it was not to use these types of automation mechanics, is there a more invisible way to do this?

**Comment by joshuatz** [comment]
When you say:

> I used it for 1 week

how exactly were you using it during that week? Using it to pull your own profile's data? Or repeatedly using it download data from _other_ people's profiles? Did you use it just a few times, or hundreds?

To be clear, this tool is meant for _personal_ use, to export your _own_ profile, not as a general purpose data scraper or profile harvester.

And even if I was unscrupulous, to answer your question, no, there is not really a more "invisible" way to do this.
