### ISSUE TITLE
Does not download all volunteer positions

### ISSUE THREAD

**Issue by fkrauthan** [joshuatz/linkedin-to-jsonresume#55]
It seems like for some reason it does not download all volunteer positions (only top 3 are included in the json).

**Comment by joshuatz** [comment]
@fkrauthan Thanks for reporting. I can confirm this issue exists - for certain items within a profile, LinkedIn will only load the first three entries, and require that subsequent entries be loaded lazily, with pagination (e.g., if you have 5 volunteer entries, you get the first 3 on the initial page load, and the final 2 have to be separately loaded).

I've added code to check if volunteer experiences are truncated, and if so, perform the necessary action to load and parse the remaining entries. This fix has been rolled into [the new `v3.0.0` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.0.0).

Thanks for reporting, and also kudos on having that many volunteer experiences! 😄

**Comment by fkrauthan** [comment]
haha thanks. Yeah I am currently redoing my website and plan to regenerate most of my about me page based on linkedin data so I've noticed that some stuff was missing :D I did actually build a quick local fix for that as well. But I was not able to figure out how to retrieve them in the proper order (the only endpoint I could find returns them in a random order).

**Comment by joshuatz** [comment]
> returns them in a random order

😬 Whoops, I'm like 99% certain I need to reopen this issue now lol. I totally forgot about ordering and although `v3.0.0` now brings in all volunteer entries, it does a direct lookup by type, which does not preserve order.

**Comment by fkrauthan** [comment]
I also tried to check what LinkedIn itself is issuing to load the rest of volunteer entries but couldn't see any API call. But to be honest a lot of the way linkedin does looks rather strange.

**Comment by joshuatz** [comment]
@fkrauthan OK, ordering should fixed now too (in [latest `v3.1.0` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.1.0)). The fix for this should actually fix ordering in a few other places, so thanks for reminding me about it!

And about the way LinkedIn internal APIs / loaders work... yeah, they are indeed strange.

**Comment by fkrauthan** [comment]
Perfect I will give this and the other ticket a try probably tomorrow :)
