### ISSUE TITLE
Feature Request: Add location to work entries

### ISSUE THREAD

**Issue by fkrauthan** [joshuatz/linkedin-to-jsonresume#58]
I've noticed that currently for each work entry it does not include location. Any chance that can be added?

**Comment by joshuatz** [comment]
Looks like this is in both the JSON Resume spec and in the LI data, so I see no reason why not... I should have included this in today's release (🤦‍♂️), but I'll try to get to this soon.

**Comment by joshuatz** [comment]
@fkrauthan This was basically a one-line fix, so I went ahead and implemented it now. See [3.2.0 release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.2.0).

**Comment by fkrauthan** [comment]
Nice that's great. Really cool project.

**Comment by fkrauthan** [comment]
Just wanted to let you know that everything works great. Thank you very much.
