### ISSUE TITLE
Missing Licenses and certifications

### ISSUE THREAD

**Issue by eNzyOfficial** [joshuatz/linkedin-to-jsonresume#59]
It seems like it's not pulling this information from the profile, would it be possible to add this to the data?

An example profile containing this section would be:
https://www.linkedin.com/in/devashish-katoriya-84699337

EDIT: Seems like it's not pulling the languages out either, only the first one

**Comment by joshuatz** [comment]
Both issues (Certifications + Languages) are now fixed [in the `v3.1.0` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.1.0).

Thanks for bringing this to my attention!

**Comment by eNzyOfficial** [comment]
Sorry to reopen this one.

https://www.linkedin.com/in/punika1988/

Not sure what the edge case is but it seems on this profile it doesn't pull all the languages. However the profile in the OP seems to work fine.

Also, thanks for the extremely fast fix!

**Comment by joshuatz** [comment]
@eNzyOfficial No worries; I appreciate the follow up and bringing the edge-case to my attention. I had missed a different way that LinkedIn was nesting the language data - now fixed [in the `v3.2.1` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.2.1).
