### ISSUE TITLE
Education not exported in JSON export

### ISSUE THREAD

**Issue by fkrauthan** [joshuatz/linkedin-to-jsonresume#60]
**Describe the issue**
I've just used the latest version and noticed that the education section is no longer populated (even though my profile should have one entry).

**Help me reproduce your issue**
Download profile with education populated

**Additional context**
This is not very important for me personally just thought I report it.

**Comment by joshuatz** [comment]
@fkrauthan Thank you very much for reporting this! This was a regression introduced by a very silly mistake on my part (typo, as part of the volunteer update). Should be fixed in [`v3.2.1` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.2.1).
