### ISSUE TITLE
Cv

### ISSUE THREAD

**Issue by Ndri128** [joshuatz/linkedin-to-jsonresume#66]
[CV Ndri_PO_PM.pdf](https://github.com/joshuatz/linkedin-to-jsonresume/files/7920383/CV.Ndri_PO_PM.pdf)
[CV Ndri_PO_PM.pdf](https://github.com/joshuatz/linkedin-to-jsonresume/files/7920386/CV.Ndri_PO_PM.pdf)
[CV Ndri_PO_PM.pdf](https://github.com/joshuatz/linkedin-to-jsonresume/files/7920388/CV.Ndri_PO_PM.pdf)

**Comment by joshuatz** [comment]
Is there a question or issue associated with this?

**Comment by joshuatz** [comment]
Closing. If you have a question or have found a bug with the extension, please provide more details.
