### ISSUE TITLE
Problem to find an email address

### ISSUE THREAD

**Issue by DanielAbsi** [joshuatz/linkedin-to-jsonresume#67]
I take the profile of someone, I tested in a linkedin email scraper, and the email was successfully found, When I use linkedin-to-jsonresume everything is scripted except the email.

**Comment by joshuatz** [comment]
- This extension is not intended to be used as an email scraper. That being said, when a profile includes a public-facing email address, this extension will include it as part of the generated JSON. But it must be *public* facing, as in, you can click the "Contact info" link at the top of the person's profile and the email shows up in the popup that appears.
- The tool that worked for you might be using third-party data, outside of LinkedIn, to link email addresses to profiles.
- Without providing me with a profile link, error message, or any sort of information related to your issue, I can't verify let alone reproduce this issue.
