### ISSUE TITLE
Bug: missing work experience

### ISSUE THREAD

**Issue by jonathanAlumot** [joshuatz/linkedin-to-jsonresume#68]
For some profiles, some work experience is missing.
In this profile, the 3rd job experience in the American express section is missing in the JSON:
![image](https://user-images.githubusercontent.com/93859351/161442638-5774eee2-f096-4e60-a979-808793b3670a.png)
![image](https://user-images.githubusercontent.com/93859351/161442635-55cabdf3-ae54-4d7a-ad27-951616f1dcc0.png)
LI URL: https://www.linkedin.com/in/lorie-grech-591b1943/
Chrome version: Version 99.0.4844.84

**Comment by joshuatz** [comment]
@jonathanAlumot Thanks for reporting. This has been patched in [the `v3.2.3` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.2.3) and I've pushed the update to the Google Webstore for them to review.
