### ISSUE TITLE
How about export profile to markdown format?

### ISSUE THREAD

**Issue by bormaxi8080** [joshuatz/linkedin-to-jsonresume#76]
Hi!

How would you feel about the idea of exporting profiles to markdown (.md) format?

It seems to me that, along with exporting to JSON and VCF, this would be an extremely useful feature.

Thanks for the answer!

**Comment by joshuatz** [comment]
While I agree that it would be useful to some users, I'm trying really hard to keep the feature scope of this project tight - i.e., just the single transformation of LinkedIn data to JSON Resume, not `LI --> JSON Resume --> Markdown`

Also, this seems like an area where there are enough external tools that can handle this and do so in a much more robust way than I would have time to implement within this extension. E.g., I would take a look at things like [HackMyResume](https://github.com/hacksalot/HackMyResume), as you should be able to take the export that my extension generates and use that tools to generate a Markdown version (or even a PDF).

**Comment by bormaxi8080** [comment]
Thanks for the clarification, HackMyResume at first glance it suits most of my tasks.
