### ISSUE TITLE
resume.json

### ISSUE THREAD

**Issue by ugurakcora** [joshuatz/linkedin-to-jsonresume#85]
{
  "$schema": "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json",
  "basics": {
    "name": "Uğur Akçora",
    "label": "Akinon şirketinde Frontend Web Developer",
    "image": "",
    "email": "uakcora97@gmail.com",
    "phone": "",
    "url": "",
    "summary": "github.com/ugurakcora\nugurakcora.github.io",
    "location": {
      "countryCode": "TR",
      "address": ""
    },
    "profiles": [
      {
        "network": "LinkedIn",
        "username": "ugurakcora",
        "url": "https://www.linkedin.com/in/ugurakcora/"
      }
    ]
  },
  "work": [
    {
      "name": "Akinon",
      "position": "Frontend Developer",
      "startDate": "2021-11-30",
      "endDate": "",
      "highlights": [],
      "url": "https://www.linkedin.com/company/akinon/",
      "location": "İstanbul, Türkiye"
    },
    {
      "name": "Pixelplus",
      "position": "Frontend Developer",
      "startDate": "2020-07-31",
      "endDate": "2021-10-31",
      "highlights": [],
      "url": "https://www.linkedin.com/company/pixelplus-interactive/",
      "location": "Maslak, İstanbul, Türkiye"
    },
    {
      "name": "Freelancer",
      "position": "Frontend Developer",
      "startDate": "2020-05-31",
      "endDate": "2020-06-30",
      "highlights": [],
      "summary": "Kullandığım Teknolojiler: HTML5, SCSS, Bootstrap4, JavaScript, JQuery, NPM, Gulp, Yarn\nhttp://garantikapi.com",
      "url": "https://www.linkedin.com/company/karim-grini-freelance/",
      "location": "İstanbul, Türkiye"
    },
    {
      "name": "NicEye Group",
      "position": "Front-End Developer",
      "startDate": "2019-05-31",
      "endDate": "2020-04-30",
      "highlights": [],
      "summary": "Kullandığım Teknolojiler: HTML5, CSS3, SCSS, Bootstrap4, JavaScript, JQuery, NPM\n\nhttps://www.tbewijzer.nl\nhttps://www.pfizer.nl/meerwetenovertbe\nhttps://www.acromegalie.be\nhttps://www.msd.com.tr\nhttps://www.msdsizinle.com\nhttps://www.elektromanya.com\nhttps://www.enbrelpfizer.ch\nhttp://www.sanslicarsamba.com/\nhttp://romatolojiatlasi.com/\nhttps://tevacanliyayin.vistream.tv\nhttps://vodafonedaramazan.vistream.tv",
      "url": "https://www.linkedin.com/company/niceyegroup/",
      "location": "Istanbul, Turkey"
    },
    {
      "name": "Alegra Digital",
      "position": "Web Developer Intern",
      "startDate": "2017-07-31",
      "endDate": "2017-09-30",
      "highlights": [],
      "summary": "HTML5\nCSS3\nJavaScript\nugurakcora.com",
      "url": "https://www.linkedin.com/company/alegradigital/",
      "location": "Istanbul, Turkey"
    },
    {
      "name": "NicEye Group",
      "position": "Intern",
      "startDate": "2014-09-30",
      "endDate": "2015-06-30",
      "highlights": [],
      "url": "https://www.linkedin.com/company/niceyegroup/",
      "location": "Istanbul, Turkey"
    }
  ],
  "volunteer": [],
  "education": [
    {
      "institution": "Anadolu Üniversitesi",
      "area": "Yönetim Bilişim Sistemleri",
      "studyType": "Lisans Derecesi",
      "startDate": "2018-12-31",
      "endDate": "2022-12-31",
      "score": "4",
      "courses": []
    },
    {
      "institution": "Kırklareli Üniversitesi",
      "area": "Bilgisayar Programlama",
      "studyType": "Önlisans",
      "startDate": "2016-12-31",
      "endDate": "2018-12-31",
      "score": "2.34",
      "courses": []
    },
    {
      "institution": "Dr. Nureddin Erk - Perihan Erk Eml",
      "area": "Ağ İşletmenliği",
      "studyType": "lise",
      "startDate": "2011-12-31",
      "endDate": "2015-12-31",
      "score": "69",
      "courses": []
    },
    {
      "institution": "Zero To Mastery Academy",
      "area": "",
      "studyType": "",
      "startDate": "2022-09-30",
      "endDate": "2024-09-30",
      "score": "",
      "courses": []
    }
  ],
  "awards": [],
  "certificates": [
    {
      "name": "Zaman Yönetimi Ve Önceliklendirme",
      "issuer": "Udemy",
      "startDate": "2021-12-31",
      "url": "https://ude.my/UC-796917c0-ef70-4150-b15a-041055e13ad9"
    },
    {
      "name": "Bootstrap 4",
      "issuer": "Udemy",
      "startDate": "2019-11-30",
      "url": "http://ude.my/UC-SCLT01DK"
    },
    {
      "name": "Uygulama Geliştirerek C# Öğrenin: A'dan Z'ye Eğitim Seti",
      "issuer": "Udemy",
      "startDate": "2019-05-31",
      "url": "http://ude.my/UC-T0LITNEQ"
    },
    {
      "name": "c# 101",
      "issuer": "Turkcell Akademi",
      "startDate": "2019-05-31"
    },
    {
      "name": "70-480 Programming in HTML5 with JavaScript and CSS3",
      "issuer": "Microsoft",
      "startDate": "2019-04-30"
    },
    {
      "name": "Web ve Mobil uygulama geliştirme",
      "issuer": "Millî Eğitim Bakanlığı",
      "startDate": "2019-04-30"
    },
    {
      "name": "Web Programlama 101 Eğitimi",
      "issuer": "Turkcell Akademi",
      "startDate": "2019-03-31"
    },
    {
      "name": "Digimath Katılım Sertifikası",
      "issuer": "İstanbul Kültür Üniversitesi",
      "startDate": "2018-11-30"
    },
    {
      "name": "İş Güvenliği ve İşçi Sağlığı",
      "issuer": "Erciyes Üniversitesi",
      "startDate": "2016-03-31"
    }
  ],
  "publications": [],
  "skills": [
    {
      "name": "Scss",
      "level": "",
      "keywords": []
    },
    {
      "name": "Tailwind",
      "level": "",
      "keywords": []
    },
    {
      "name": "SCSS",
      "level": "",
      "keywords": []
    },
    {
      "name": "PUG",
      "level": "",
      "keywords": []
    },
    {
      "name": "Less",
      "level": "",
      "keywords": []
    },
    {
      "name": "Bootstrap",
      "level": "",
      "keywords": []
    },
    {
      "name": "Jinja2",
      "level": "",
      "keywords": []
    },
    {
      "name": "Python",
      "level": "",
      "keywords": []
    },
    {
      "name": "Django",
      "level": "",
      "keywords": []
    },
    {
      "name": "HTML5",
      "level": "",
      "keywords": []
    },
    {
      "name": "CSS",
      "level": "",
      "keywords": []
    },
    {
      "name": "JavaScript",
      "level": "",
      "keywords": []
    },
    {
      "name": "HTML",
      "level": "",
      "keywords": []
    },
    {
      "name": "jQuery",
      "level": "",
      "keywords": []
    },
    {
      "name": "Git",
      "level": "",
      "keywords": []
    },
    {
      "name": "Bootstrap 4",
      "level": "",
      "keywords": []
    },
    {
      "name": "Pug",
      "level": "",
      "keywords": []
    },
    {
      "name": "XML",
      "level": "",
      "keywords": []
    },
    {
      "name": "XSLT",
      "level": "",
      "keywords": []
    },
    {
      "name": "C#",
      "level": "",
      "keywords": []
    },
    {
      "name": "İngilizce",
      "level": "",
      "keywords": []
    },
    {
      "name": "Gulp",
      "level": "",
      "keywords": []
    },
    {
      "name": "JIRA",
      "level": "",
      "keywords": []
    },
    {
      "name": "Dart",
      "level": "",
      "keywords": []
    },
    {
      "name": "Npm",
      "level": "",
      "keywords": []
    }
  ],
  "languages": [
    {
      "language": "tr",
      "fluency": "Native Speaker"
    },
    {
      "fluency": "Native Speaker",
      "language": "Türkçe"
    },
    {
      "fluency": "Limited Working",
      "language": "İngilizce"
    }
  ],
  "interests": [],
  "references": [],
  "projects": [
    {
      "name": "Houseofsuperstep",
      "startDate": "2022-10-31",
      "summary": "site geliştirmeler",
      "url": "http://houseofsuperstep.com.tr",
      "endDate": "2022-10-31"
    },
    {
      "name": "Converse",
      "startDate": "2022-01-31",
      "summary": "Site geliştirmeleri",
      "url": "http://converse.com.tr",
      "endDate": "2022-01-31"
    },
    {
      "name": "Kooples",
      "startDate": "2022-01-31",
      "summary": "Checkout - Order Cancellation Development",
      "url": "http://thekooples.com.tr",
      "endDate": "2022-01-31"
    },
    {
      "name": "Superstep",
      "startDate": "2021-11-30",
      "summary": "Müşteriden gelen geliştirmeler yapıldı.",
      "url": "https://www.superstep.com.tr/",
      "endDate": "2022-05-31"
    },
    {
      "name": "SuperStep House",
      "startDate": "2022-01-31",
      "summary": "Superstep House firmasının ana sayfa kodlanması.",
      "url": "https://www.superstephouse.com",
      "endDate": "2022-01-31"
    },
    {
      "name": "AmericanExpress",
      "startDate": "2021-10-31",
      "summary": "JavaScript yazılması gerektiği yerlerde geliştirmeler yapıldı. Kart başvurusu sayfası kodlandı",
      "url": "https://americanexpress.com.tr",
      "endDate": "2021-10-31"
    },
    {
      "name": "Boytrans",
      "startDate": "2021-05-31",
      "summary": "Erciyes Anadolu Holding bünyesinde bulunan Boytrans firması için; Adobe XD üzerinden gelen tasarımı Pug, Scss, JS, Jquery kullanarak mobile first kodladım. CMS tarafında XSLT ile entegrasyon yapıldı.",
      "url": "https://www.boytrans.com.tr/tr/",
      "endDate": "2021-10-31"
    },
    {
      "name": "Tüyap",
      "startDate": "2021-03-31",
      "summary": "Tüyap kurumsal ve etkinlik sitelerinde CMS ve site geliştirmeleri yapıldı",
      "url": "https://tuyap.com.tr",
      "endDate": "2021-10-31"
    },
    {
      "name": "Boyser",
      "startDate": "2021-01-31",
      "summary": "Erciyes Anadolu Holding bünyesinde bulunan Boyser firmasının web sitesini kodlarken Pug, Scss, JavaScript ve Jquery kullandım. CMS entegrasyonunda XSLT kullandım",
      "url": "https://www.boyser.com.tr",
      "endDate": "2021-09-30"
    },
    {
      "name": "Form Sünger",
      "startDate": "2020-09-30",
      "summary": "Erciyes Anadolu Holding bünyesinde bulunan Vellteks firmasının kurumsal web sitesini tasarımı Adobe XD üzerinden iletilen projeyi kodlarken Pug, Scss, Js ve Jquery kullandım. CMS kurulumu ve yapısını hazırlayarak dinamik bir web sitesi haline getirdim.",
      "url": "https://www.formsunger.com.tr",
      "endDate": "2021-07-31"
    },
    {
      "name": "Kemerli Grup",
      "startDate": "2021-07-31",
      "summary": null,
      "url": "https://kemerli.com.tr",
      "endDate": "2021-07-31"
    },
    {
      "name": "Vellteks",
      "startDate": "2020-09-30",
      "summary": "Erciyes Anadolu Holding bünyesinde bulunan Vellteks firmasının kurumsal web sitesini tasarımı Adobe XD üzerinden iletilen projeyi kodlarken Pug, Scss, Js ve Jquery kullandım.",
      "url": "https://vellteks.com.tr",
      "endDate": "2021-06-30"
    },
    {
      "name": "Uzman Sosyal Güvenlik",
      "startDate": "2021-01-31",
      "summary": "Pug, Scss, Bootstrap Grid, JavaScript ve JQuery kullanılarak web sitesi çıkarıldı, hâlâ devam ediyorum ve yapım aşamasındadır.",
      "url": "https://uzmansosyalguvenlik.com",
      "endDate": "2021-01-31"
    },
    {
      "name": "Garanti Kapı",
      "startDate": "2020-05-31",
      "summary": "HTML5 CSS3 JS ile responsive kurumlar web site tasarımı ve kodlaması gerçekleştirdim.",
      "url": "http://garantikapi.com/",
      "endDate": "2020-06-30"
    },
    {
      "name": "MSD",
      "startDate": "2019-07-31",
      "summary": "HTML5 ve CSS3 kullanarak sayfalar oluşturuyorum.",
      "url": "http://msd.com.tr",
      "endDate": "2020-04-30"
    },
    {
      "name": "MSD Sizinle",
      "startDate": "2019-07-31",
      "summary": "HTML5, CSS3, JavaScript ve Jquery kullanarak sayfalar oluşturuyorum.",
      "url": "http://msdsizinle.com",
      "endDate": "2020-04-30"
    },
    {
      "name": "Pfizer Acromegalie",
      "startDate": "2019-07-31",
      "summary": "Pfizer sitesi olan acromegalie.be'nin HTML, CSS, JavaScript ve Jquery kodları yazıldı.",
      "url": "http://acromegalie.be",
      "endDate": "2020-04-30"
    },
    {
      "name": "Pfizer Enbrel",
      "startDate": "2019-07-31",
      "summary": "HTML, CSS ve JavaScript kullanılarak Pfizer şirketine ait bir site yapıldı.",
      "url": "https://enbrelpfizer.ch",
      "endDate": "2020-04-30"
    },
    {
      "name": "Pfizer Tbewijzer",
      "startDate": "2019-06-30",
      "summary": "Pfizer'in web sitesi olan tbewijzer.nl'de HTML, CSS ve JavaScript kodları yazıldı.",
      "url": "http://tbewijzer.nl",
      "endDate": "2020-04-30"
    },
    {
      "name": "Romatoloji Atlası",
      "startDate": "2020-03-31",
      "summary": null,
      "url": "http://romatolojiatlasi.com",
      "endDate": "2020-04-30"
    }
  ],
  "meta": {
    "version": "v1.0.0",
    "canonical": "https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json"
  }
}

**Comment by joshuatz** [comment]
Is there a question or issue associated with this?
