### ISSUE TITLE
CvChef de projet

### ISSUE THREAD

**Issue by Gwenlbjvb** [joshuatz/linkedin-to-jsonresume#92]

**Comment by joshuatz** [comment]
@Gwenlbjvb Is there a specific question I can help you with? I'm not sure what it is based on the issue title alone.

**Comment by Gwenlbjvb** [comment]
Sorrry to have bothered you for nothing, It's a mistake trying to export my linkedin cv to json ! 
Have a good day 
Gwen 


De: "Joshua Tzucker" ***@***.***> 
À: "joshuatz/linkedin-to-jsonresume" ***@***.***> 
Cc: "Gwen Le Bloa (maison)" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 27 Mai 2024 20:03:12 
Objet: Re: [joshuatz/linkedin-to-jsonresume] CvChef de projet (Issue #92) 





[ https://github.com/Gwenlbjvb | @Gwenlbjvb ] Is there a specific question I can help you with? I'm not sure what it is based on the issue title alone.
